### ISSUE TITLE
Get live streak and best streak from numbers not squares

### ISSUE THREAD

**Issue by jollyra** [jollyra/hubot-commit-streak#8]
This should speed things up.

**Comment by supermitch** [comment]
:+1:

**Comment by jollyra** [comment]
This has the opposite effect - it's slows waaaay down. Turns out scraping a user's entire page is slower than scraping just a small svg. 

I'm going to use the contribution calendar calculation for current streaks, but I'll have to use the full page scrape for longest streak.
